<?php if ( ! defined( 'ABSPATH' ) ) {
	exit;} // Exit if accessed directly

require_once plugin_dir_path( __FILE__ ) . 'class-ovas-connect-api-fields.php';

class Ovas_Connect_Contacts extends Ovas_Connect_api_Fields {
	protected $fields      = array(
		'contactId'         => array(
			'validationInsert' => 'notAllowed',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'nullFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'id',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'contactFunctionId' => array(
			'validationInsert' => 'required,isNumeric,listItemExists',
			'validationUpdate' => 'required,isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'id_function',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/contactfunctions',
		),
		'genderId'          => array(
			'validationInsert' => 'isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'id_sexe',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/genders',
		),
		'initials'          => array(
			'validationInsert' => 'required',
			'validationUpdate' => 'required',
			'convertToDB'      => 'initialsFLD,ucfirstFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'initials',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'firstname'         => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD,ucfirstFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'firstname',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'intersert'         => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'intersert',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'lastname'          => array(
			'validationInsert' => 'required',
			'validationUpdate' => 'required',
			'convertToDB'      => 'stringFLD,ucfirstFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'name',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'dateOfBirth'       => array(
			'validationInsert' => 'dateFLD',
			'validationUpdate' => 'dateFLD',
			'convertToDB'      => 'dateFLD',
			'convertFromDB'    => 'dateFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'dateofbirth',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'email'             => array(
			'validationInsert' => 'emailFLD',
			'validationUpdate' => 'dateFLD',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'email',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'telephone'         => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'telephone',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'mobile'            => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'mobile',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'fax'               => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'fax',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'bankaccount'       => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'bankaccount',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'iban'              => array(
			'validationInsert' => 'ibanFLD',
			'validationUpdate' => 'ibanFLD',
			'convertToDB'      => 'stringFLD,uppercaseFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'iban',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'bic'               => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD,uppercaseFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'bic',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'notes'             => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_contacts',
			'databaseColumn'   => 'notes',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
	);
	public $uri            = array(
		'GET'    => '/relations/{relationId}/contacts',
		'POST'   => '/relations/{relationId}/contacts/',
		'PUT'    => '/relations/{relationId}/contacts/{id}',
		'DELETE' => '/relations/{relationId}/contacts/{id}',
	);
	public $name           = 'Contacts';
	public $label          = 'Contacts';
	public $order          = 10;
	protected $returnField = 'contactId';

	// Hardcoded string needed for WP translation
	public function getLabel() {
		return __( 'Contacts', 'ovas-connect' );
	}
}
