<?php if ( ! defined( 'ABSPATH' ) ) {
	exit;} // Exit if accessed directly

require_once plugin_dir_path( __FILE__ ) . 'class-ovas-connect-api-fields.php';

class Ovas_Connect_Projects extends Ovas_Connect_api_Fields {
	protected $fields = array(
		'projectId'       => array(
			'validationInsert' => 'notAllowed',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'nullFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'id',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'projectNumber'   => array(
			'validationInsert' => 'required,isNumeric',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'projectnr',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'projectCode'     => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'projectcode',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'projectStatusId' => array(
			'validationInsert' => 'required,isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'id_project_status',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/projectstatus',
		),
		'ledgerId'        => array(
			'validationInsert' => 'required,isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'id_gb',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/ledgers',
		),
		'costtypeId'      => array(
			'validationInsert' => 'isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'id_kpl',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '/costtypes',
		),
		'responseId'      => array(
			'validationInsert' => 'isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'id_response',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '/responses',
		),
		'title'           => array(
			'validationInsert' => 'required',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'title',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'description'     => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'description',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'descriptionEn'   => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'description_en',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'price'           => array(
			'validationInsert' => 'amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'price',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'contractPrice'   => array(
			'validationInsert' => 'amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'contract_price',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'provision'       => array(
			'validationInsert' => 'amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'provision',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'overhead'        => array(
			'validationInsert' => 'amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'overhead',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'transportCosts'  => array(
			'validationInsert' => 'amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'transportcosts',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'result'          => array(
			'validationInsert' => 'amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'result',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'startDate'       => array(
			'validationInsert' => 'dateFLD',
			'validationUpdate' => 'dateFLD',
			'convertToDB'      => 'dateFLD',
			'convertFromDB'    => 'dateFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'startdate',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'endDate'         => array(
			'validationInsert' => 'dateFLD',
			'validationUpdate' => 'dateFLD',
			'convertToDB'      => 'dateFLD',
			'convertFromDB'    => 'dateFLD',
			'databaseTable'    => 'tbl_projects',
			'databaseColumn'   => 'enddate',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
	);

	public $uri            = array(
		'GET'    => '/locations/{locationId}/projects/{id}',
		'POST'   => '/locations/{locationId}/projects',
		'PUT'    => '/locations/{locationId}/projects/{id}',
		'DELETE' => '/locations/{locationId}/projects/{id}',
	);
	public $name           = 'Projects';
	public $label          = 'Add Project';
	public $order          = 73;
	protected $returnField = 'projectId';

	// Hardcoded string needed for WP translation
	public function getLabel() {
		return __( 'Add Project', 'ovas-connect' );
	}
}
