<?php if ( ! defined( 'ABSPATH' ) ) {
	exit;} // Exit if accessed directly

require_once plugin_dir_path( __FILE__ ) . 'class-ovas-connect-api-fields.php';

class Ovas_Connect_Relations extends Ovas_Connect_api_Fields {
	protected $fields = array(
		'relationId'                              => array(
			'validation'     => 'notAllowed',
			'convertToDB'    => 'nullFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'relationTypeId'                          => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_reltype',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/relationtypes',
		),
		'relationStatusId'                        => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_status',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/relationstatus',
		),
		'relationTitleId'                         => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_title',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/relationtitles',
		),
		'genderId'                                => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_sexe',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/genders',
		),
		'maritalStatusId'                         => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_marital_status',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/maritalstatus',
		),
		'religiousStatusId'                       => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religious_status',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousstatus',
		),
		'religiousDenominationId'                 => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religious_denomination',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousdenominations',
		),
		'pastoralUnitTitle'                       => array(
			'validation'     => 'required',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_pe',
			'databaseColumn' => 'nr',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'familyRelationshipId'                    => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_pe',
			'databaseColumn' => 'id_pe_gezinsrelatie',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/familyrelationships',
		),
		'sectorId'                                => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_sector',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/sectors',
		),
		'subSectorId'                             => array(
			'validation'     => 'isNumeric,listItemExists,subSectorFLD',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_subsector',
			'required'       => true,
			'linkedTo'       => 'sectorId',
			'linkhref'       => '/sectors/{sectorId}/subsectors',
		),
		'companyName'                             => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'company',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'companySubname'                          => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'company2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'cocNumber'                               => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'kvk',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'vatNumber'                               => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'vat',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'relationNumber'                          => array(
			'validation'     => 'isNumeric',
			'convertToDB'    => 'numericFLD',
			'convertFromDB'  => 'numericFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'regnr',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'initials'                                => array(
			'validation'     => '',
			'convertToDB'    => 'initialsFLD,ucfirstFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'initials',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'officialname'                            => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,ucfirstFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'fullinitials',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'firstname'                               => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,ucfirstFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'firstname',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'intersert'                               => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'intersert',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'lastname'                                => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,ucfirstFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'name',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'intersertPartner'                        => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'intersert_partner',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'lastnamePartner'                         => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,ucfirstFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'name_partner',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'nameUsageId'                             => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_name_usage',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/nameusage',
		),
		'street'                                  => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,ucfirstFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'street',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'number'                                  => array(
			'validation'     => 'isNumeric',
			'convertToDB'    => 'numericFLD',
			'convertFromDB'  => 'numericFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'nr',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'addon'                                   => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'nraddon',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'zip'                                     => array(
			'validation'     => 'zipFLD',
			'convertToDB'    => 'stringFLD,uppercaseFLD,zipFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'zip',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'residence'                               => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'residence',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'countryId'                               => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_country',
			'required'       => true,
			'linkedTo'       => '',
			'linkhref'       => '/countries',
		),
		'visitStreet'                             => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'street2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'visitNumber'                             => array(
			'validation'     => 'isNumeric',
			'convertToDB'    => 'numericFLD',
			'convertFromDB'  => 'numericFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'nr2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'visitAddon'                              => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'nraddon2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'visitZip'                                => array(
			'validation'     => 'zipFLD',
			'convertToDB'    => 'stringFLD,uppercaseFLD,zipFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'zip2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'visitResidence'                          => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'residence2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'visitCountryId'                          => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_country2',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/countries',
		),
		'email'                                   => array(
			'validation'     => 'emailFLD',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'email',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'website'                                 => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'website',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'telephone'                               => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'telephone',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'mobile'                                  => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'mobile',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'fax'                                     => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'fax',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'bankaccount'                             => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'bankaccount',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'iban'                                    => array(
			'validation'     => 'ibanFLD',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'iban',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'bic'                                     => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'bic',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'notes'                                   => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'notes',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'thanks'                                  => array(
			'validation'     => 'booleanFLD',
			'convertToDB'    => 'booleanFLD',
			'convertFromDB'  => 'booleanFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'thanks',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'noEmail'                                 => array(
			'validation'     => 'booleanFLD',
			'convertToDB'    => 'booleanFLD',
			'convertFromDB'  => 'booleanFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'nodigital',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'noLetters'                               => array(
			'validation'     => 'booleanFLD',
			'convertToDB'    => 'booleanFLD',
			'convertFromDB'  => 'booleanFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'noletter',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'dateOfBirth'                             => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofbirth',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfBirth'                            => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofbirth',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'dateOfRegistration'                      => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofregistration',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfRegistration'                     => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofregistration',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'religiousDenominationOfRegistration'     => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religiousofregistration',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousdenominations',
		),
		'dateOfDeregistration'                    => array(
			'validation'     => 'isDate',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofderegistration',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfDeregistration'                   => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofderegistration',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'religiousDenominationOfDeregistration'   => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religiousofderegistration',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousdenominations',
		),
		'dateOfBaptism'                           => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofbaptize',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfBaptism'                          => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofbaptize',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'religiousDenominationOfBaptism'          => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religiousofbaptize',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousdenominations',
		),
		'dateOfConfession'                        => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofconfession',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfConfession'                       => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofconfession',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'religiousDenominationOfConfession'       => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religiousofconfession',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousdenominations',
		),
		'dateOfWedding'                           => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofwedding',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfWedding'                          => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofwedding',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'dateOfReligiousWedding'                  => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofreligiouswedding',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfReligiousWedding'                 => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofreligiouswedding',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'religiousDenominationOfReligiousWedding' => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'id_religiousofreligiouswedding',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/religiousdenominations',
		),
		'dateOfDivorce'                           => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofdivorce',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfDivorce'                          => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofdivorce',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'reasonOfDivorce'                         => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'reasonofdivorce',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'dateOfDeceased'                          => array(
			'validation'     => 'dateFLD',
			'convertToDB'    => 'dateFLD',
			'convertFromDB'  => 'dateFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'dateofdeceased',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'placeOfDeceased'                         => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD,uppercaseFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'placeofdeceased',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'reasonOfDeceased'                        => array(
			'validation'     => '',
			'convertToDB'    => 'stringFLD',
			'convertFromDB'  => 'stringFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'reasonofdeceased',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'creditor'                                => array(
			'validation'     => 'booleanFLD',
			'convertToDB'    => 'booleanFLD',
			'convertFromDB'  => 'booleanFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'creditor',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'debtor'                                  => array(
			'validation'     => 'booleanFLD',
			'convertToDB'    => 'booleanFLD',
			'convertFromDB'  => 'booleanFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'debtor',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'creditorPayterm'                         => array(
			'validation'     => 'isNumeric',
			'convertToDB'    => 'numericFLD',
			'convertFromDB'  => 'numericFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'creditor_default_payterm',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '',
		),
		'defaultReceiptsLedger'                   => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'creditor_default_id_gb',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/ledgers',
		),
		'defaultPaymentsLedger'                   => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'debtor_default_id_gb',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/ledgers',
		),
		'defaultReceiptsCosttype'                 => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'creditor_default_id_kpl',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/costtypes',
		),
		'defaultPaymentsCosttype'                 => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'debtor_default_id_kpl',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/costtypes',
		),
		'defaultReceiptsResponse'                 => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'creditor_default_id_response',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/responses',
		),
		'defaultPaymentsResponse'                 => array(
			'validation'     => 'isNumeric,listItemExists',
			'convertToDB'    => 'intFLD',
			'convertFromDB'  => 'intFLD',
			'databaseTable'  => 'tbl_relations',
			'databaseColumn' => 'debtor_default_id_response',
			'required'       => false,
			'linkedTo'       => '',
			'linkhref'       => '/responses',
		),
	);

	protected $typefields = array( 'relationId', 'relationNumber', 'relationTypeId', 'relationStatusId', 'relationTitleId', 'genderId', 'initials', 'firstname', 'intersert', 'lastname', 'dateOfBirth', 'street', 'number', 'addon', 'zip', 'residence', 'countryId', 'email', 'telephone', 'mobile', 'fax', 'notes', 'bankaccount', 'iban', 'bic', 'thanks', 'noEmail', 'noLetters', 'debtor', 'creditor', 'creditorPayterm', 'defaultReceiptsLedger', 'defaultPaymentsLedger', 'defaultReceiptsCosttype', 'defaultPaymentsCosttype', 'defaultReceiptsResponse', 'defaultPaymentsResponse' );

	public $uri = array(
		'GET'    => '/relations/{id}',
		'POST'   => '/relations/',
		'PUT'    => '/relations/{id}',
		'DELETE' => '/relations/{id}',
	);

	public $name           = 'Relations_private';
	public $label          = 'Add relation (private)';
	public $order          = 3;
	protected $returnField = 'relationId';
	protected $apiFieldMap = array(
		'countryId' => array(
			'AW' => 146,
			'BE' => 18,
			'BR' => 27,
			'CA' => 34,
			'DK' => 46,
			'DE' => 50,
			'FR' => 63,
			'IT' => 93,
			'LU' => 119,
			'NL' => 146,
			'NO' => 157,
			'AT' => 163,
			'PL' => 171,
			'ES' => 192,
			'GB' => 224,
			'ZA' => 233,
			'SE' => 236,
			'CH' => 237,
		),
	);

	// Hardcoded string needed for WP translation
	public function getLabel() {
		return __( 'Add relation (private)', 'ovas-connect' );
	}
}
