<?php if ( ! defined( 'ABSPATH' ) ) {
	exit;} // Exit if accessed directly
require_once plugin_dir_path( __FILE__ ) . 'class-ovas-connect-api-fields.php';

class Ovas_Connect_Adoptions extends Ovas_Connect_api_Fields {
	protected $fields = array(
		'adoptionId'       => array(
			'validationInsert' => 'notAllowed',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'nullFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'id',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'adoptionNumber'   => array(
			'validationInsert' => 'notAllowed',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'nullFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'adoptnr',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'adoptionCode'     => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'adoptcode',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'adoptionTypeId'   => array(
			'validationInsert' => 'required,isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'id_adoption_type',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/adoptiontypes',
		),
		'adoptionStatusId' => array(
			'validationInsert' => 'isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'id_adoption_status',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/adoptionstatus',
		),
		'projectId'        => array(
			'validationInsert' => 'notAllowed',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'nullFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'id_project',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'genderId'         => array(
			'validationInsert' => 'required,isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'id_sexe',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/genders',
		),
		'firstname'        => array(
			'validationInsert' => 'required',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'firstname',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'intersert'        => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'intersert',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'surname'          => array(
			'validationInsert' => 'required',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'name',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'nickname'         => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'nickname',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'residence'        => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'residence',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'dateOfBirth'      => array(
			'validationInsert' => 'dateFLD',
			'validationUpdate' => 'dateFLD',
			'convertToDB'      => 'dateFLD',
			'convertFromDB'    => 'dateFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'dateofbirth',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'dateOfOrigin'     => array(
			'validationInsert' => 'notAllowed',
			'validationUpdate' => 'notAllowed',
			'convertToDB'      => 'dateFLD',
			'convertFromDB'    => 'dateFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'dateoforigin',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'endDate'          => array(
			'validationInsert' => 'dateFLD',
			'validationUpdate' => 'dateFLD',
			'convertToDB'      => 'dateFLD',
			'convertFromDB'    => 'dateFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'enddate_sponsoring',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'neededAmount'     => array(
			'validationInsert' => 'required,amountFLD',
			'validationUpdate' => 'amountFLD',
			'convertToDB'      => 'amountFLD',
			'convertFromDB'    => 'numericFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'needed_amount',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'frequencyId'      => array(
			'validationInsert' => 'required,isNumeric,listItemExists',
			'validationUpdate' => 'isNumeric,listItemExists',
			'convertToDB'      => 'intFLD',
			'convertFromDB'    => 'intFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'id_frequency',
			'required'         => true,
			'linkedTo'         => '',
			'linkhref'         => '/promisesfrequencies',
		),
		'description'      => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'description',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'descriptionEn'    => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'description_en',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'notes'            => array(
			'validationInsert' => '',
			'validationUpdate' => '',
			'convertToDB'      => 'stringFLD',
			'convertFromDB'    => 'stringFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'notes',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
		'showOnWebsite'    => array(
			'validationInsert' => 'booleanFLD',
			'validationUpdate' => 'booleanFLD',
			'convertToDB'      => 'booleanFLD',
			'convertFromDB'    => 'booleanFLD',
			'databaseTable'    => 'tbl_adoption',
			'databaseColumn'   => 'show_on_website',
			'required'         => false,
			'linkedTo'         => '',
			'linkhref'         => '',
		),
	);

	public $uri            = array(
		'GET'    => '/projects/{projectId}/adoptions/{id}',
		'POST'   => '/projects/{projectId}/adoptions',
		'PUT'    => '/projects/{projectId}/adoptions/{id}',
		'DELETE' => '/projects/{projectId}/adoptions/{id}',
	);
	public $name           = 'Adoptions';
	public $label          = 'Adoptions';
	public $order          = 81;
	protected $returnField = 'adoptionId';

	// Hardcoded string needed for WP translation
	public function getLabel() {
		return __( 'Adoptions', 'ovas-connect' );
	}
}
